---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: bookstack
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "true"
spec:
  releaseName: bookstack
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: bookstack
    version: 0.27.5
  values: {}
