---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: bookstack
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "true"
spec:
  releaseName: bookstack
  chart:
    git: git@github.com:helm/charts
    path: charts/stable/bookstack
    ref: 83fa6578f516ad0909592a43960affafec299441
  values: {}
